### ISSUE TITLE
フォントの指定

### ISSUE THREAD

**Issue by mkpoli** [typst-jp/typst-jp.github.io#17]
現状では日本語フォントが指定されておらず、ブラウザーのデフォルトフォントになっているのですが、欧文は HK Grotesk のままで、食い合わせが悪いため、いい感じの日本語フォント（UD系とか？）にしたいですね……

**Comment by mkpoli** [comment]
フォント指定箇所、`HR Grotesk`, `Inter` など
* [static/styles/docs.css](https://github.com/typst-jp/typst-jp.github.io/blob/407a3ba107e4c1e1c9d3981713e7b9e41c66b07f/static/styles/docs.css#L797)
* [static/styles/default.css](https://github.com/typst-jp/typst-jp.github.io/blob/407a3ba107e4c1e1c9d3981713e7b9e41c66b07f/static/styles/default.css#L74)
* [templates/base_template.html.j2](https://github.com/typst-jp/typst-jp.github.io/blob/407a3ba107e4c1e1c9d3981713e7b9e41c66b07f/templates/base_template.html.j2#L33)
* [static/docs/index.html](https://github.com/typst-jp/typst-jp.github.io/blob/407a3ba107e4c1e1c9d3981713e7b9e41c66b07f/static/docs/index.html#L34)
* [static/docs/reference/types/index.html](https://github.com/typst-jp/typst-jp.github.io/blob/407a3ba107e4c1e1c9d3981713e7b9e41c66b07f/static/docs/reference/types/index.html#L31)
* static/docs/reference/types/*/index.html

**Comment by mkpoli** [comment]
`BIZ UDGothic` 割と合うんじゃないですか？
![image](https://github.com/user-attachments/assets/fb8bd0d9-6eaf-4e92-9713-ae042e68539a)

**Comment by m-tsuru** [comment]
確かに，日本語フォントを指定することはとても有用なのですが，例えば，`BIZ UD(P)ゴシック` は， macOS 標準ではインストールされていないなど，微妙に扱いづらい部分はあると思います．

それを回避するために，Google Fonts などからフォントをダウンロードするよう仕向けることも可能ではありますが，通信帯域を消費するという意味で優れた解決策とはなりにくいです．（スマートフォン等で調べたいときにサイズの大きなフォントを落とされるのはナンセンス）

個人的には，`BIZ UD(P) ゴシック, ヒラギノ角ゴシック, Noto Sans JP, sans-serif` などのように順々に OS に存在するフォントにフォールバックしていくような指定が好ましく思います．

**Comment by mkpoli** [comment]
Mac系のフォントは`..., system-ui, -apple-system, BlinkMacSystemFont, ...`で指定したほうが望ましいので、`"BIZ UDGothic", "BIZ UDPGothic"`だけを美術的選択として、非強制的（Webフォントを使わずに）指定して、その２つのフォントがない場合はシステムにお任せしたいと思います
