### ISSUE TITLE
CI/CD に失敗する

### ISSUE THREAD

**Issue by kimushun1101** [typst-jp/typst-jp.github.io#37]
2024/07/25 に Rust が 1.80.0 となりました。
https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html

その影響からか以下のエラーで CD に失敗するようになりました。
https://github.com/typst-jp/typst-jp.github.io/actions/runs/10122472646/job/27994654742

```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.20/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

#36 で Rust のバージョンを 1.77 に固定するという暫定的な対処を行いました。
https://github.com/typst-jp/typst-jp.github.io/pull/36/files
1.77 とした理由は、投稿者のローカル環境が 1.77 で動作検証ができたからです。  
試行錯誤的に一つずつバージョンを上げることもできるかもしれませんが、そこまで詰める需要もないと思いましたのでとりあえずということで。

バージョン 1.77 で問題なければそのまま使い続けるという選択もできますが、根本的な解決としては以下が考えられます。
1. 以降のバージョン 1.80.1 や 1.81.0 などで後方互換性が復活した場合、該当修正をもとに戻す。
2. [Cargo.toml](https://github.com/typst-jp/typst-jp.github.io/blob/719ab4b9a62360afb453cc3f5127ebfc511102a9/Cargo.toml) を整備して Cargo.lock を更新する。
3. そもそも上記の前提が間違えており、異なる対処で解決する。

ご助言などありましたらよろしくお願いいたします。

**Comment by 3w36zj6** [comment]
本家リポジトリの最新の変更を取り込むまでの間は、コードに手を加えずにビルドが成功するバージョンで固定する方針が良いと思います。

**Comment by kimushun1101** [comment]
#40 で [.github/workflows/ci.yml](https://github.com/typst-jp/typst-jp.github.io/blob/407a3ba107e4c1e1c9d3981713e7b9e41c66b07f/.github/workflows/ci.yml) が追加されたことにより CI が失敗します。

#36 で直した[ .github/workflows/deploy.yml](https://github.com/typst-jp/typst-jp.github.io/blob/407a3ba107e4c1e1c9d3981713e7b9e41c66b07f/.github/workflows/deploy.yml) は問題なく動いているため Pull Request 上ではわかりにくいと思いますが、一例として以下のページから確認できると思います。
https://github.com/kimushun1101/typst-jp.github.io/actions/runs/10535838558

---

## 対策案1
マージ前のように、deploy.yml だけ残し、ci.yml docker-image.yml, release.yml を削除する。
https://github.com/typst-jp/typst-jp.github.io/blob/06b658a10780700bf71a66a5d9550447543a76f9/.github/workflows/deploy.yml
お手軽なためこの repository で今後 ci.yml などを使う見込みがないのであればこちらをオススメしたい。

## 対策案2
#36 で行ったように ci.yml docker-image.yml, release.yml を直す。
ただし、以前とは違う種類エラー文も出ているため、すぐできるかはちょっとわかりません。

**Comment by 3w36zj6** [comment]
`.github/workflows/`にあるワークフロー定義のうちこのリポジトリで不要なものは削除しておきたいところですが、上流ブランチをマージする際に毎回不要なファイルを確認して削除をするのが面倒なので、このリポジトリの[https://github.com/typst-jp/typst-jp.github.io/actions](Actions)でDisabledにしておくと良いかもしれません。
