### ISSUE TITLE
目次を日本語化する

### ISSUE THREAD

**Issue by mkpoli** [typst-jp/typst-jp.github.io#46]
右の目次は現状英語のままで、どうにかできないものでしょうか。

![image](https://github.com/user-attachments/assets/ca2875d3-e3fc-48a5-b121-971ebf6827d8)

**Comment by kimushun1101** [comment]
ちゃんとソースコードを読んでいないのでわかりませんが、ここの `#when-typst` とか `#learnings` を日本語にすればいいという話ですかね？日本語だと弾かれたりしますかね？
https://github.com/typst-jp/typst-jp.github.io/blob/407a3ba107e4c1e1c9d3981713e7b9e41c66b07f/docs/tutorial/welcome.md?plain=1#L13-L18

取り急ぎ確認したければデプロイしてみるのが早そうですが、コミットログを汚してしまうので、やはり #28 などで議論されているようにローカル仮想環境がほしいですね。
Web 周りは詳しくないのでご助言いただけます嬉しいです。

**Comment by gomazarashi** [comment]
![image](https://github.com/user-attachments/assets/3ecef2fe-29eb-4ec2-a114-f486147507bb)
中国語版においても目次の翻訳が行われていないことや、例えば[スクリプト記述](https://typst-jp.github.io/docs/reference/scripting/)のページ等でのページ内リンクの際に指定されているIDが目次の[Fields](https://typst-doc-cn.github.io/docs/reference/scripting/#fields)などと同名であることに鑑みると、日本語に置換してしまうと不具合が発生してしまう可能性はあります。とはいえ私もドキュメントを生成するうえでどのようにIDを決定しているのかについては理解しきれていないため憶測にはなってしまいますが...

**Comment by mkpoli** [comment]
かるく覗いてみたところ、以下が問題箇所のようです

https://github.com/typst-jp/typst-jp.github.io/blob/0562cd585577038472744ea9cd9bd0854b938491/templates/base_template.html.j2?plain=1#L166-L176

**Comment by mkpoli** [comment]
さらに調べていくと、この`outline`は`docs/src/lib.rs`の`PageModel`のフィールドで扱われます

https://github.com/typst-jp/typst-jp.github.io/blob/0562cd585577038472744ea9cd9bd0854b938491/docs/src/lib.rs#L113-L128

さらに、`Html`の中では`Handler`によって`outline`が決まります

https://github.com/typst-jp/typst-jp.github.io/blob/0562cd585577038472744ea9cd9bd0854b938491/docs/src/html.rs#L102

`Handler`では`handle_heading()`によってMarkdownの見出しが扱われ、`outline`に追加されます。

https://github.com/typst-jp/typst-jp.github.io/blob/0562cd585577038472744ea9cd9bd0854b938491/docs/src/html.rs#L286C8-L327

`{ name }`がここで扱われます。`to_title_case`の過程で非英数字が落ちたと思われます。

https://github.com/typst-jp/typst-jp.github.io/blob/0562cd585577038472744ea9cd9bd0854b938491/docs/src/html.rs#L310-L315
