### ISSUE TITLE
日本語中に出てくる英字の取り扱いについて

### ISSUE THREAD

**Issue by kimushun1101** [typst-jp/typst-jp.github.io#58]
#18 でご議論頂いた方々を Assignees として設定しております。
翻訳ガイドラインの改定について提案いたします。

現在
https://github.com/typst-jp/typst-jp.github.io/blob/045d003ed0702d4a9c5c647128cd4871418a1e76/CONTRIBUTING.md?plain=1#L80
となっていますが、英語との間には半角スペースを挿入する方が一般的であると思われます。
そのように改定してもよろしいでしょうか？ご議論いただけますと幸いです。

---

参考までに、翻訳ガイドラインの参考にありますリンク先では以下のように記述されております。（一部抜粋）
* [WordPress 翻訳ハンドブック](https://ja.wordpress.org/team/handbook/translation/)
  > 頭以外の英字、記号の前後には半角スペースを入れる。例: 警告 !、WordPress ドキュメンテーション
* [Vue.js 公式サイト日本語翻訳ガイド](https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md)
  > ### 半角スペースでアルファベット両端を入れて読みやすく！
  > > Vue.js is a library for building modern web interfaces.
  > 
  > - NG : Vue.jsはモダンなWebインターフェースを構築するためのライブラリーです。
  > 
  > - OK : Vue.js はモダンな Web インターフェースを構築するためのライブラリーです。
  > 
  > 例外として、句読点の前後にアルファベットがある場合は、スペースを入れなくてもいいです。
  > 
  > - 読点: 技術的に、Vue.js は MVVM パターンの ViewModel レイヤーに注目しています。
* [ja.react.dev 翻訳スタイルガイド](https://github.com/reactjs/ja.react.dev/wiki/%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89)
  > 英数字と和文との間には半角スペースを入れる。ただし他の約物（特に句読点 。, 、）と直接隣接している場合は不要。
  > > React␣の␣API␣で、`fooBar`␣を␣1␣回実行。

**Comment by kimushun1101** [comment]
実は #34 ではこのルールをすっかり読み落としていて半角スペースが入っております。
#57 では現在のルールに従い、半角スペースを入れておりません。
ここで決定されたルールに従い、他のページも合わせて修正いたします。

**Comment by mkpoli** [comment]
> Based on Disscussion on Discord, the consensus are towarding not inserting half-width space (U+0020) manually.
> 
> https://discord.com/channels/1196431244158849064/1251938021314400306/1254457656500949152
> 
_Originally posted by @mkpoli in https://github.com/typst-jp/typst-jp.github.io/issues/18#issuecomment-2185149124_

以上#18の通り、今までコンベンションとして、半角スペースを挿入する方が一般的ではありますが、それはあくまでレンダリングエンジンが正しく文字種間の空白を挿入できなかった歴史による間に合せの解決案であり、セマンティック上`U+0020`を挿入すべきではありません（なぜなら日本語の中に例えば英語を埋め込む場合は、あくまで日本語であり、日本語は単語間のスペースを入れないので、英語をひとかたまりとしての日本語の単語として見る場合は、入れてしまえば日本語の単語の間にスペースを入れてしまうことになり、不一致が起きるからです）。また、Typstは組版エンジンである背景を鑑みて、JTF標準などでは`U+0020`を入れないのが普通で、入れないほうがプロフェッショナルです。さらに、近年では[Chromeなどで試験的に`text-autospace`が導入され](https://developer.chrome.com/blog/css-i18n-features?hl=ja)（[`text-autospace`](https://www.w3.org/TR/css-text-4/#propdef-text-autospace)はCSS Text Module Level 4 
[W3C Working Draft](https://www.w3.org/standards/types#WD)の一部として定義されています。）

**Comment by kimushun1101** [comment]
@mkpoli 
ありがとうございます！読み落としていました。
後ほど #34 の方を修正してPull Requestを出します。
