### ISSUE TITLE
Typstでの日本語組版ノウハウの専用ページを作る

### ISSUE THREAD

**Issue by stepney141** [typst-jp/typst-jp.github.io#9]
中国語版では、`docs/chinese.md`として、Typstでの中国語組版のコツを解説する[専用ページを設けています](https://typst-doc-cn.github.io/docs/chinese/)。日本語版では、この内容を日本語の組版に書き換える必要があります。その内容を議論する場所としてこのIssueを建てておきます。

なお、日本語版では当然ながらMarkdownファイルを`japanese.md`にリネームする必要があります。しかし、fork元の関係上、このリポジトリにおけるWebページ生成システムは「`chinese.md`が存在していること」を前提とした処理になっているようです。そのため、ただMarkdownファイルを作り直すだけでは正しくWebページが生成されず、リポジトリの各所を改造する必要がある点に注意が必要です。

**Comment by mkpoli** [comment]
私が書いた記事含め、特にZennやQiitaの日本語関係のTypst記事やUniverseなどに上がっているパッケージやテンプレートを、上手い具合に引用・紹介していけたらいいかなと思います

https://zenn.dev/topics/typst
https://qiita.com/tags/typst
https://typst.app/universe/search?q=japanese

**Comment by kimushun1101** [comment]
@stepney141 @mkpoli @3w36zj6 
こちらのIssueは、まだ残しておきますか？
- #74 である程度対応できたかと思われますがいかがでしょうか？

**Comment by 3w36zj6** [comment]
このIssueは完了として、新しいコンテンツの追加や改修の要望があるときには新しいIssueを作成する運用が良いかもしれません。
